spring:
  application:
    name: spring-jwt
  datasource:
    url: jdbc:mysql://localhost:3300/spring_jwt?createDatabaseIfNotExist=true
    username: root
    password: s3cr3t
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#  security:
#    user:
#      password: admin123$

server:
  port: 8000





